/** Offline recorder, not a Phaser/WebGL renderer. Production views own commands. */
import type Phaser from 'phaser';
export type RecordCommand = { type:string; args:unknown[]; fill?:unknown; stroke?:unknown; alpha?:number; width?:number; shadowBlur?:number; shadowColor?:string; composite?:string };
export class CanvasCommands {
 commands:RecordCommand[]=[]; fillStyle:unknown='#000'; strokeStyle:unknown='#000'; globalAlpha=1; globalCompositeOperation='source-over';shadowBlur=0;shadowColor='rgba(0,0,0,0)'; lineWidth=1; path:RecordCommand[]=[];
 private push(type:string,args:unknown[]){this.commands.push({type,args,fill:this.fillStyle,stroke:this.strokeStyle,alpha:this.globalAlpha,width:this.lineWidth,shadowBlur:this.shadowBlur,shadowColor:this.shadowColor,composite:this.globalCompositeOperation});}
 fillRect(...args:number[]){this.push('fillRect',args);}clearRect(...args:number[]){this.push('clearRect',args);}strokeRect(...args:number[]){this.push('strokeRect',args);}
 createRadialGradient(...args:number[]){return {type:'radialGradient',args,stops:[] as unknown[],addColorStop(offset:number,color:string){this.stops.push([offset,color]);}};}
 beginPath(){this.path=[];}ellipse(...args:number[]){this.path.push({type:'ellipse',args});}arc(...args:number[]){this.path.push({type:'arc',args});}moveTo(...args:number[]){this.path.push({type:'moveTo',args});}lineTo(...args:number[]){this.path.push({type:'lineTo',args});}closePath(){this.path.push({type:'closePath',args:[]});}fill(){this.push('fillPath',this.path);}stroke(){this.push('strokePath',this.path);}
}
export type TextureRecord={key:string;width:number;height:number;url?:string;commands?:RecordCommand[];frames:Record<string,{x:number;y:number;width:number;height:number}>};
export class Surface {
 kind='image';x=0;y=0;width=1;height=1;scaleX=1;scaleY=1;rotation=0;alpha=1;depth=0;visible=true;destroyed=false;originX=.5;originY=.5;tint=0xffffff;tintMode=0;blendMode=0;flipX=false;flipY=false;parented=false;crop:{x:number;y:number;width:number;height:number}|null=null;texture={key:''};frame={name:'__BASE'};data:Record<string,unknown>={};
 constructor(readonly textures:Map<string,TextureRecord>,key='',x=0,y=0){this.x=x;this.y=y;if(key)this.setTexture(key);}
 setTexture(key:string){this.texture={key};const t=this.textures.get(key);if(!t)throw new Error(`Missing offline texture ${key}`);this.width=t.width;this.height=t.height;this.frame={name:'__BASE'};return this;}setFrame(name:string){this.frame={name};const f=this.textures.get(this.texture.key)?.frames[name];if(f){this.width=f.width;this.height=f.height;}return this;}
 setPosition(x:number,y:number){this.x=x;this.y=y;return this;}setOrigin(x:number,y=x){this.originX=x;this.originY=y;return this;}setScale(x:number,y=x){this.scaleX=x;this.scaleY=y;return this;}setDisplaySize(w:number,h:number){return this.setScale(w/this.width,h/this.height);}setDepth(v:number){this.depth=v;return this;}setAlpha(v:number){this.alpha=v;return this;}setVisible(v:boolean){this.visible=v;return this;}setBlendMode(v:number){this.blendMode=v;return this;}setTint(v:number){this.tint=v;return this;}clearTint(){this.tint=0xffffff;return this;}setTintMode(v:number){this.tintMode=v;return this;}setRotation(v:number){this.rotation=v;return this;}setAngle(v:number){this.rotation=v*Math.PI/180;return this;}setFlipX(v:boolean){this.flipX=v;return this;}setFlipY(v:boolean){this.flipY=v;return this;}setCrop(x:number,y:number,width:number,height:number){this.crop={x,y,width,height};return this;}setScrollFactor(){return this;}setData(k:string,v:unknown){this.data[k]=v;return this;}getData(k:string){return this.data[k];}destroy(){this.destroyed=true;this.visible=false;}
}
export class GraphicsSurface extends Surface {
 override kind='graphics';commands:RecordCommand[]=[];fill=0;fillAlpha=1;stroke=0;strokeAlpha=1;strokeWidth=1;path:number[]=[];
 clear(){this.commands=[];return this;}fillStyle(c:number,a=1){this.fill=c;this.fillAlpha=a;return this;}lineStyle(w:number,c:number,a=1){this.strokeWidth=w;this.stroke=c;this.strokeAlpha=a;return this;}
 private push(type:string,args:unknown[],stroke=false){this.commands.push({type,args,fill:stroke?this.stroke:this.fill,alpha:stroke?this.strokeAlpha:this.fillAlpha,width:stroke?this.strokeWidth:0});return this;}
 fillRect(...a:number[]){return this.push('fillRect',a);}strokeRect(...a:number[]){return this.push('strokeRect',a,true);}fillRoundedRect(...a:number[]){return this.push('fillRoundedRect',a);}strokeRoundedRect(...a:number[]){return this.push('strokeRoundedRect',a,true);}fillCircle(...a:number[]){return this.push('fillCircle',a);}strokeCircle(...a:number[]){return this.push('strokeCircle',a,true);}fillEllipse(...a:number[]){return this.push('fillEllipse',a);}strokeEllipse(...a:number[]){return this.push('strokeEllipse',a,true);}fillTriangle(...a:number[]){return this.push('polygon',a);}fillPoints(points:{x:number;y:number}[]){return this.push('polygon',points.flatMap(p=>[p.x,p.y]));}strokePoints(points:{x:number;y:number}[],close=false){return this.push(close?'strokePolygon':'polyline',points.flatMap(p=>[p.x,p.y]),true);}lineBetween(...a:number[]){return this.push('polyline',a,true);}beginPath(){this.path=[];return this;}moveTo(x:number,y:number){this.path.push(x,y);return this;}lineTo(x:number,y:number){this.path.push(x,y);return this;}closePath(){this.path.push(...this.path.slice(0,2));return this;}strokePath(){return this.push('polyline',[...this.path],true);}
}
export class ContainerSurface extends Surface {override kind='container';children:Surface[]=[];get list(){return this.children;}add(c:Surface|Surface[]){for(const n of Array.isArray(c)?c:[c]){n.parented=true;this.children.push(n);}return this;}remove(child:Surface,destroy=false){const at=this.children.indexOf(child);if(at>=0)this.children.splice(at,1);child.parented=false;if(destroy)child.destroy();return this;}override destroy(children=false){super.destroy();if(children)for(const c of this.children)c.destroy();}}
export class MapSurface extends Surface {override kind='lightmap';ambient=0;stamps:unknown[]=[];clear(){this.stamps=[];return this;}fill(color:number){this.ambient=color;return this;}stamp(key:string,frame:unknown,x:number,y:number,options:unknown){this.stamps.push({key,frame,x,y,options});return this;}render(){return this;}}
export function lightingRenderer(assetRecords:TextureRecord[]=[]){
 const textures=new Map<string,TextureRecord>(assetRecords.map(a=>[a.key,a])), roots:Surface[]=[];
 textures.set('__DEFAULT',{key:'__DEFAULT',width:32,height:32,commands:[],frames:{}});
 const add=<T extends Surface>(n:T)=>{roots.push(n);return n;};
 const scene={textures:{exists:(k:string)=>textures.has(k),get:(k:string)=>{const t=textures.get(k);if(!t)throw new Error(`Get missing texture ${k}`);return {...t,getSourceImage:()=>({width:t.width,height:t.height}),has:(name:string)=>name in t.frames,add:(name:string,_index:number,x:number,y:number,width:number,height:number)=>{t.frames[name]={x,y,width,height};}};},createCanvas:(key:string,width:number,height:number)=>{const ctx=new CanvasCommands();textures.set(key,{key,width,height,commands:ctx.commands,frames:{}});return {getContext:()=>ctx,refresh:()=>{}};}},add:{image:(x:number,y:number,key:string,frame?:string)=>{const n=add(new Surface(textures,key,x,y));if(frame)n.setFrame(frame);return n;},graphics:()=>add(new GraphicsSurface(textures)),container:(x=0,y=0)=>{const c=add(new ContainerSurface(textures));c.x=x;c.y=y;return c;},layer:()=>{const c=add(new ContainerSurface(textures));c.kind='layer';return c;},tileSprite:(x:number,y:number,w:number,h:number,key:string)=>{const n=add(new Surface(textures,key,x,y));n.kind='tile';n.width=w;n.height=h;return n;},renderTexture:(x:number,y:number,w:number,h:number)=>{const n=add(new MapSurface(textures));Object.assign(n,{x,y,width:w,height:h});return n;},rectangle:(x:number,y:number,w:number,h:number,color:number,alpha=1)=>{const n=add(new GraphicsSurface(textures));n.fillStyle(color,alpha).fillRect(x-w/2,y-h/2,w,h);(n as unknown as Record<string,unknown>).setFillStyle=(c:number,a=1)=>{n.clear().fillStyle(c,a).fillRect(x-w/2,y-h/2,w,h);return n;};return n;}},time:{now:10000},scale:{width:960,height:600},cameras:{main:{shake:()=>{},worldView:{x:0,y:-120,right:960,bottom:480}}},children:{list:roots},sys:{displayList:{add:(n:Surface)=>{n.parented=false;if(!roots.includes(n))roots.push(n);return n;},get list(){return roots.filter(n=>!n.parented&&!n.destroyed);}}}} as unknown as Phaser.Scene;
 function encode(n:Surface):unknown {const {textures:_,...rest}=n;return {...rest,...(n instanceof ContainerSurface?{children:n.children.map(encode)}:{})};}
 return {scene,textures,roots,encode:()=>roots.filter(n=>!n.parented).map(encode)};
}
