import {describe,it,expect,vi} from 'vitest';
vi.mock('phaser',()=>({default:{Input:{Keyboard:{KeyCodes:{TAB:9}}},BlendModes:{ADD:1},Math:{Vector2:class{constructor(public x:number,public y:number){}}}}}));
import {GameHud} from '../../src/game/ui/GameHud';
import {createMvpRun} from '../../src/sim/run/createMvpRun';
import {hudRenderer} from '../support/hud-renderer';
import {enterDoorway, tickMvpRun} from '../../src/sim/run/tickMvpRun';
import {enterStore} from '../../src/sim/run/storeInterior';
import {buildGameHudModel} from '../../src/game/ui/gameHudModel';
import {DEFAULT_SETTINGS,gameSettings} from '../../src/game/settings/settings';
import {NO_PERKS} from '../../src/sim/run/perks';
import type {MvpRunState} from '../../src/sim/run/types';
function setup(){const r=hudRenderer();const hud=new GameHud(r.scene);hud.setCoachAllowed(false);const state=createMvpRun(7);state.room.combat.enemies=[];state.room={...state.room,variantId:'prop-test'};hud.sync(state);state.tick=600;hud.sync(state);return {...r,hud,state};}
function own(state:MvpRunState,ids:string[]){state.inventory={...state.inventory,inventory:ids.map((id,i)=>({kind:'leaf' as const,instanceId:`item-${i}`,itemDefinitionId:id,acquisitionKind:'purchased' as const,sourceLocationId:'test',sourceStockId:`stock-${i}`,acquisitionTick:0})),selectedPrimaryInstanceId:'item-0'};}
function visibleHearts(r:ReturnType<typeof setup>){return r.images.filter(i=>i.visible&&!i.destroyed&&i.texture.key.startsWith('hud:heart'));}
describe('mall-directory HUD renderer',()=>{
 it('renders all six maximum-health hearts and hides surplus hearts after restart',()=>{const r=setup();r.state.perks={...NO_PERKS,bonusHealth:6};r.state.room.combat.player.health=11;r.hud.sync(r.state);expect(visibleHearts(r)).toHaveLength(6);expect(visibleHearts(r).at(-1)?.texture.key).toBe('hud:heart-half');r.state=createMvpRun(8);r.hud.sync(r.state);expect(visibleHearts(r)).toHaveLength(3);});
 it('shows one shared attack countdown and distinct dash-active/recovery/ready states',()=>{const r=setup();r.state.room.combat.player.attackCooldownTicks=7;r.state.room.combat.player.dashTicks=3;r.state.room.combat.player.dashCooldownTicks=40;r.hud.sync(r.state);expect(r.text()).toContain('ATTACK 0.2S');expect(r.text()).toContain('DASHING');r.state.room.combat.player.dashTicks=0;r.hud.sync(r.state);expect(r.text()).toContain('DASH 0.7S');r.state.room.combat.player.attackCooldownTicks=0;r.state.room.combat.player.dashCooldownTicks=0;r.hud.sync(r.state);expect(r.text()).toContain('ATTACK READY');expect(r.text()).toContain('DASH READY');});
 it('fits nine weapons and twelve passives without crossing the stage or colliding with vitals',()=>{const r=setup();own(r.state,[...Array(9).fill('janitor_mop'),...Array(12).fill('gel_pens')]);r.hud.sync(r.state);const icons=r.images.filter(i=>i.visible&&i.texture.key.startsWith('neon:item:'));expect(icons).toHaveLength(21);for(const i of icons){expect(i.x-i.width*i.scaleX/2).toBeGreaterThanOrEqual(240);expect(i.x+i.width*i.scaleX/2).toBeLessThanOrEqual(706);expect(i.y+i.height*i.scaleY/2).toBeLessThanOrEqual(588);}expect(new Set(icons.map(i=>`${i.x},${i.y}`)).size).toBe(21);});
 it('keeps an equipped weapon past nine visible and click-selectable without a false digit shortcut',()=>{const r=setup();own(r.state,Array(14).fill('janitor_mop'));r.state.inventory={...r.state.inventory,selectedPrimaryInstanceId:'item-13'};r.hud.sync(r.state);const icon=r.images.filter(i=>i.visible&&i.texture.key==='neon:item:mop').at(-1)!;expect(r.hud.weaponSlotAt(icon.x,icon.y)).toBe(14);expect(r.text()).toContain('14');expect(r.text().some(t=>t.includes('OF 14'))).toBe(true);});
 it('uses a question glyph for a missing weapon icon and keeps its hit box',()=>{const r=setup();r.missing.add('neon:item:mop');r.state.tick++;r.state.cash++;r.hud.sync(r.state);expect(r.text()).toContain('?');expect(r.hud.weaponSlotAt(274,562)).toBe(1);});
 it('keeps collapsed corner chips below the reserved PA ticker lane',()=>{const r=setup();const top=r.labels().filter(i=>i.y<100);expect(top.length).toBeGreaterThan(0);expect(top.every(i=>i.y>=34)).toBe(true);});
 it('bounds long wanted objectives within their directory panel',()=>{const r=setup();r.state.heat=85;r.peek.isDown=true;r.hud.sync(r.state);const line=r.labels().find(i=>i.texture.key.includes('LOSS PREVENTION ON YOU'));expect(line).toBeDefined();expect(line!.x+line!.width).toBeLessThanOrEqual(286);});
 it('does not lose a receipt character at a wrapped line boundary',()=>{const r=setup();r.state.recentChange='ABCDEFGHIJ ABCDEFGHIJ ABCDEFGHIJ X END';r.state.tick++;r.hud.sync(r.state);const paper=r.labels().filter(i=>i.y>=560&&i.y<585&&i.x===734).map(i=>i.texture.key.slice(6).split('|')[0]);expect(paper.join(' ').replaceAll(' ','')).toBe(r.state.recentChange.replaceAll(' ',''));});
 it('keeps shop notes inside the offer card and above a crowded dock',()=>{const r=setup();own(r.state,[...Array(9).fill('janitor_mop'),...Array(12).fill('gel_pens')]);for(let i=0;i<6&&!r.state.wing.rooms[r.state.roomIndex]?.store;i++){r.state.room.combat.enemies=[];enterDoorway(r.state,'east');}enterStore(r.state);const offer=r.state.wing.rooms[r.state.roomIndex]!.offers[0]!;r.state.room.combat.player.x=offer.position.x;r.state.room.combat.player.y=offer.position.y;r.state.cash=0;r.hud.sync(r.state);const note=buildGameHudModel(r.state).prompt!.detail!.note;const labels=r.labels().filter(i=>i.x===306&&i.texture.key.includes('NEED $'));expect(labels.length).toBeGreaterThan(0);for(const i of r.labels().filter(i=>i.x===306)){expect(i.x+i.width).toBeLessThanOrEqual(748);}expect(r.text().join(' ')).toContain(note);});
 it.each([false,true])('keeps a sparse shop card clear of the wanted strip (paired=%s)',(paired)=>{const r=setup();for(let i=0;i<6&&!r.state.wing.rooms[r.state.roomIndex]?.store;i++){r.state.room.combat.enemies=[];enterDoorway(r.state,'east');}enterStore(r.state);const offer=r.state.wing.rooms[r.state.roomIndex]!.offers.find(o=>o.position.y<=200)!;expect(offer).toBeDefined();if(paired)r.state={...r.state,wing:{...r.state.wing,rooms:r.state.wing.rooms.map((room,idx)=>idx===r.state.roomIndex?{...room,offers:room.offers.map(o=>o.id===offer.id?{...o,itemDefinitionId:'janitor_mop',pairedWith:'plasma_globe'}:o)}:room)}};r.state.room.combat.player.x=offer.position.x;r.state.room.combat.player.y=offer.position.y;r.state.heat=40;r.hud.sync(r.state);if(paired)expect(buildGameHudModel(r.state).prompt!.detail!.pair).toContain('SHOCK MOP');const offerPanel=r.graphics[0]!.commands.find(c=>c.type==='fillRect'&&c.args[0]===200&&c.args[2]===560)!;expect(offerPanel).toBeDefined();expect(offerPanel.args[1]!+offerPanel.args[3]!).toBeLessThanOrEqual(458);});
 it('preserves simulation, pause, hiding, proximity fading and destruction',()=>{const r=setup();const before=JSON.stringify(r.state);r.hud.sync(r.state);expect(JSON.stringify(r.state)).toBe(before);r.state.room.combat.player.y=400;r.hud.sync(r.state);expect(r.containers[1]?.alpha).toBe(.4);r.state.paused=true;r.hud.sync(r.state);const labels=r.text();r.hud.sync(r.state);expect(r.text()).toEqual(labels);r.hud.setHidden(true);expect(r.containers[0]?.visible).toBe(false);r.hud.setHidden(false);expect(r.containers[0]?.visible).toBe(true);r.hud.destroy();expect(r.images.every(i=>i.destroyed)).toBe(true);});
});

describe('HUD inventory and lifecycle edge cases',()=>{
 it.each([2,3,4,5,6])('renders every health state at a %s-heart maximum',heartCount=>{const r=setup();r.state=createMvpRun(7,{perks:{...NO_PERKS,bonusHealth:Math.max(0,heartCount-3)*2},...(heartCount===2?{rule:'glass' as const}:{})});for(let hp=0;hp<=heartCount*2;hp++){r.state.room.combat.player.health=hp;r.hud.sync(r.state);const hearts=visibleHearts(r);expect(hearts).toHaveLength(heartCount);expect(hearts.filter(h=>h.texture.key==='hud:heart-full')).toHaveLength(Math.floor(hp/2));expect(hearts.filter(h=>h.texture.key==='hud:heart-half')).toHaveLength(hp%2);}});
 it('clears old click boxes and icon stamps when a crowded inventory shrinks',()=>{const r=setup();own(r.state,[...Array(9).fill('janitor_mop'),...Array(15).fill('gel_pens')]);r.hud.sync(r.state);expect(r.text()).toContain('+4');expect(r.hud.weaponSlotAt(268,570)).toBe(6);own(r.state,['janitor_mop']);r.hud.sync(r.state);expect(r.hud.weaponSlotAt(324,562)).toBeNull();expect(r.text()).not.toContain('+4');expect(r.images.filter(i=>i.visible&&i.texture.key.startsWith('neon:item:'))).toHaveLength(1);});
 it('labels actual fused and hot weapons and preserves their real slot selection',()=>{const r=setup();own(r.state,['janitor_mop','pump_soaker','box_cutter']);const [mop,soaker,cutter]=r.state.inventory.inventory;r.state.inventory={...r.state.inventory,inventory:[{kind:'composite',instanceId:'fusion',recipeId:'hybrid',createdTick:0,transactionId:'fusion-tx',primary:mop!,carrier:soaker!},{...cutter!,acquisitionKind:'stolen'} as typeof cutter],selectedPrimaryInstanceId:'fusion'} as MvpRunState['inventory'];r.hud.sync(r.state);expect(r.text()).toContain('FUSED');expect(r.text()).toContain('HOT');expect(r.text()).toContain('HYDRO MOP');expect(r.hud.weaponSlotAt(324,562)).toBe(2);r.state.inventory={...r.state.inventory,selectedPrimaryInstanceId:'item-2'};r.hud.sync(r.state);expect(r.text()).toContain('BOX CUTTER');expect(r.text().filter(t=>t.startsWith('ATTACK '))).toHaveLength(1);});
 it('retains TAB disclosure and exact frozen readiness through pause and room transitions',()=>{const r=setup();expect(r.text()).not.toContain('TONIGHT');r.peek.isDown=true;r.hud.sync(r.state);expect(r.text()).toContain('TONIGHT');r.peek.isDown=false;r.state.paused=true;r.state.room.combat.player.attackCooldownTicks=8;r.hud.sync(r.state);const before=r.text();r.hud.sync(r.state);expect(r.text()).toEqual(before);r.state.paused=false;r.state.room.combat.enemies=[];enterDoorway(r.state,'east');r.hud.sync(r.state);expect(r.text()).toContain('ATTACK READY');});
});


describe('HUD comfort and full simulation preservation',()=>{
 it('avoids portrait hit-flashing in the reduced-flash setting',()=>{gameSettings().update({...DEFAULT_SETTINGS,flashes:'reduced'});try{const r=setup();r.state.room.combat.player.invulnerableTicks=12;r.state.tick=612;r.hud.sync(r.state);expect(r.images.find(i=>i.texture.key==='neon:portrait:alex')!.tint).toBe(0xffffff);}finally{gameSettings().update(DEFAULT_SETTINGS);}});
 it('keeps 720 full run states identical with the renderer active',()=>{for(const seed of [1,7,42]){const r=hudRenderer();const hud=new GameHud(r.scene);hud.setCoachAllowed(false);const observed=createMvpRun(seed),control=createMvpRun(seed);for(let tick=0;tick<240;tick++){const input={moveX:tick%90<45?1:-1,moveY:tick%120<60?.3:-.3,aimX:800,aimY:240,fire:tick%3!==1,dash:tick%80===0,interact:false,steal:false,recall:false};tickMvpRun(observed,input);tickMvpRun(control,input);hud.sync(observed);expect(observed).toEqual(control);}hud.destroy();}});
});

describe('receipt and directory typography',()=>{
 it('uses each pale backing color instead of a black halo around small dark text',()=>{const r=setup();r.state.recentChange='Picked up $4.';r.state.tick++;r.hud.sync(r.state);const equipped=r.labels().find(i=>i.texture.key.startsWith('label:EQUIPPED|'))!;expect(equipped.texture.key.split('|').at(-1)).toBe('#71b8b5');const receipt=r.labels().find(i=>i.x===734&&i.y===562)!;expect(receipt.texture.key.split('|').at(-1)).toBe('#d6d0b7');});
});
